import type { Sector, Cohort, CompanyBase, CohortBias } from './types';

export const SECTORS: Sector[] = [
  { id: 'ai',      label: 'AI Lab',    tint: 'oklch(0.95 0.04 290)', fg: 'oklch(0.4 0.15 290)' },
  { id: 'quant',   label: 'Quant',     tint: 'oklch(0.95 0.04 145)', fg: 'oklch(0.4 0.15 145)' },
  { id: 'bigtech', label: 'Big Tech',  tint: 'oklch(0.95 0.03 250)', fg: 'oklch(0.4 0.12 250)' },
  { id: 'unicorn', label: 'Unicorn',   tint: 'oklch(0.95 0.04 60)',  fg: 'oklch(0.42 0.12 60)' },
  { id: 'startup', label: 'Startup',   tint: 'oklch(0.95 0.04 25)',  fg: 'oklch(0.45 0.15 25)' },
  { id: 'public',  label: 'Public',    tint: 'oklch(0.95 0.02 0)',   fg: 'oklch(0.4 0.02 0)' },
  { id: 'hardware',label: 'Hardware',  tint: 'oklch(0.95 0.03 200)', fg: 'oklch(0.4 0.12 200)' },
  { id: 'crypto',  label: 'Crypto',    tint: 'oklch(0.95 0.04 80)',  fg: 'oklch(0.45 0.15 80)' },
];

export const COHORTS: Cohort[] = [
  { id: 'all',     label: 'Everyone' },
  { id: 'swe',     label: 'SWE' },
  { id: 'pm',      label: 'PM' },
  { id: 'quant',   label: 'Quant' },
  { id: 'design',  label: 'Design' },
  { id: 'newgrad', label: 'New Grad' },
  { id: 'senior',  label: 'Senior+' },
];

function defaultBias(sector: string): CohortBias {
  switch (sector) {
    case 'quant':   return { swe: -40,  pm: -80, quant: +220, design: -120, newgrad: -30, senior: +40 };
    case 'ai':      return { swe: +30,  pm: +10, quant: -20,  design: +20,  newgrad: +50, senior: +20 };
    case 'bigtech': return { swe: 0,    pm: +30, quant: -10,  design: +20,  newgrad: +40, senior: -10 };
    case 'unicorn': return { swe: +20,  pm: +40, quant: -20,  design: +60,  newgrad: +30, senior: +10 };
    case 'startup': return { swe: +10,  pm: +20, quant: -40,  design: +30,  newgrad: -10, senior: +20 };
    case 'public':  return { swe: -10,  pm: 0,   quant: 0,    design: 0,    newgrad: +20, senior: 0 };
    case 'hardware':return { swe: -10,  pm: 0,   quant: -20,  design: -10,  newgrad: 0,   senior: +20 };
    case 'crypto':  return { swe: 0,    pm: -10, quant: +40,  design: -20,  newgrad: +10, senior: -20 };
    default:        return { swe: 0,    pm: 0,   quant: 0,    design: 0,    newgrad: 0,   senior: 0 };
  }
}

type RawCompany = [string, string, string, string, number];

const RAW: RawCompany[] = [
  // AI labs
  ['openai',     'OpenAI',              'Frontier models, ChatGPT, the AGI race.',              'ai', 1820],
  ['anthropic',  'Anthropic',           'Constitutional AI; Claude.',                           'ai', 1810],
  ['deepmind',   'DeepMind',            'Google’s research lab; AlphaFold, Gemini.',       'ai', 1780],
  ['xai',        'xAI',                 'Grok, Colossus supercluster.',                         'ai', 1640],
  ['mistral',    'Mistral',             'Open-weight models out of Paris.',                     'ai', 1660],
  ['cohere',     'Cohere',              'Enterprise LLMs, retrieval.',                          'ai', 1560],
  ['hf',         'Hugging Face',        'The model hub everyone uses.',                         'ai', 1640],
  ['perplexity', 'Perplexity',          'AI answer engine.',                                    'ai', 1620],
  ['character',  'Character.AI',        'Companion chatbots.',                                  'ai', 1480],
  ['scale',      'Scale AI',            'Data labeling for frontier models.',                   'ai', 1560],
  ['runway',     'Runway',              'Generative video.',                                    'ai', 1580],
  ['midjourney', 'Midjourney',          'Generative imagery, profitable and tiny.',             'ai', 1700],
  ['stability',  'Stability AI',        'Stable Diffusion lineage.',                            'ai', 1420],
  ['inflection', 'Inflection',          'Pi, then absorbed into Microsoft.',                    'ai', 1430],
  ['adept',      'Adept',               'Agents; talent acquired by Amazon.',                   'ai', 1410],
  ['ai21',       'AI21 Labs',           'Jurassic LLMs out of Tel Aviv.',                       'ai', 1480],
  ['together',   'Together AI',         'Open-model inference at scale.',                       'ai', 1540],
  // Quant
  ['janestreet', 'Jane Street',         'OCaml-pilled prop trading shop.',                      'quant', 1820],
  ['citadel',    'Citadel',             'Ken Griffin’s hedge fund + market maker.',        'quant', 1780],
  ['citsec',     'Citadel Securities',  'The market-making sibling.',                           'quant', 1770],
  ['twosigma',   'Two Sigma',           'Quant fund, ML-heavy.',                                'quant', 1730],
  ['jump',       'Jump Trading',        'Low-latency Chicago prop shop.',                       'quant', 1720],
  ['hrt',        'Hudson River Trading','HFT, deeply C++.',                                     'quant', 1740],
  ['deshaw',     'D. E. Shaw',          'Quant fund + research arm.',                           'quant', 1710],
  ['rentec',     'Renaissance Tech',    'Medallion. Famously closed.',                          'quant', 1800],
  ['optiver',    'Optiver',             'Market maker out of Amsterdam.',                       'quant', 1660],
  ['imc',        'IMC',                 'Options market maker.',                                'quant', 1620],
  ['tower',      'Tower Research',      'HFT, Latour subsidiary.',                              'quant', 1590],
  ['sig',        'Susquehanna',         'SIG; poker-pilled trader culture.',                    'quant', 1640],
  ['akuna',      'Akuna Capital',       'Options market making, Chicago.',                      'quant', 1520],
  ['drw',        'DRW',                 'Don Wilson’s prop shop.',                         'quant', 1620],
  ['flowtraders','Flow Traders',        'ETF market maker.',                                    'quant', 1480],
  ['virtu',      'Virtu Financial',     'Public market maker.',                                 'quant', 1460],
  ['millennium', 'Millennium',          'Multi-strat hedge fund.',                              'quant', 1680],
  ['baly',       'Balyasny',            'Multi-manager fund.',                                  'quant', 1560],
  ['point72',    'Point72',             'Steve Cohen’s hedge fund.',                       'quant', 1620],
  ['pdt',        'PDT Partners',        'Quant fund spun out of Morgan Stanley.',               'quant', 1640],
  // Big tech
  ['google',     'Google',              'Search, ads, infra. Still the campus.',                'bigtech', 1700],
  ['meta',       'Meta',                'FB, IG, WA, Reality Labs.',                            'bigtech', 1660],
  ['apple',      'Apple',               'Hardware + ecosystem, secrecy.',                       'bigtech', 1720],
  ['amazon',     'Amazon',              'AWS, retail, ads.',                                    'bigtech', 1580],
  ['microsoft',  'Microsoft',           'Azure, Office, Copilot.',                              'bigtech', 1680],
  ['netflix',    'Netflix',             'Streaming + the famous comp band.',                    'bigtech', 1660],
  ['nvidia',     'Nvidia',              'GPUs, CUDA, the picks-and-shovels king.',              'bigtech', 1800],
  ['tesla',      'Tesla',               'EVs, autonomy, Optimus.',                              'bigtech', 1500],
  ['oracle',     'Oracle',              'Databases, cloud, Larry Ellison.',                     'bigtech', 1380],
  ['salesforce', 'Salesforce',          'CRM mothership.',                                      'bigtech', 1420],
  ['adobe',      'Adobe',               'Creative Cloud + Figma drama.',                        'bigtech', 1460],
  ['intel',      'Intel',               'x86 incumbent. Foundry pivot.',                        'bigtech', 1320],
  ['amd',        'AMD',                 'Ryzen, MI300, Lisa Su era.',                           'bigtech', 1540],
  ['ibm',        'IBM',                 'Mainframes, consulting, Watson.',                      'bigtech', 1300],
  ['samsung',    'Samsung',             'Foundry, displays, devices.',                          'bigtech', 1380],
  ['tsmc',       'TSMC',                'The fab. Everyone depends on it.',                     'bigtech', 1680],
  ['arm',        'Arm',                 'IP licensor. Powers every phone.',                     'bigtech', 1540],
  ['bytedance',  'ByteDance',           'TikTok parent. China + global.',                       'bigtech', 1580],
  ['tencent',    'Tencent',             'WeChat, games, investments.',                          'bigtech', 1500],
  ['alibaba',    'Alibaba',             'Cloud, commerce, Ant.',                                'bigtech', 1440],
  // Unicorns
  ['stripe',     'Stripe',              'Payments infra; the engineer’s favorite.',        'unicorn', 1780],
  ['figma',      'Figma',               'Collaborative design.',                                'unicorn', 1720],
  ['notion',     'Notion',              'Docs + databases.',                                    'unicorn', 1640],
  ['linear',     'Linear',              'The issue tracker people actually love.',              'unicorn', 1720],
  ['vercel',     'Vercel',              'Next.js + frontend cloud.',                            'unicorn', 1660],
  ['supabase',   'Supabase',            'Open-source Firebase, Postgres-first.',                'unicorn', 1620],
  ['ramp',       'Ramp',                'Corporate cards, finance ops.',                        'unicorn', 1640],
  ['mercury',    'Mercury',             'Banking for startups.',                                'unicorn', 1600],
  ['brex',       'Brex',                'Spend management for startups.',                       'unicorn', 1480],
  ['retool',     'Retool',              'Internal tools, fast.',                                'unicorn', 1560],
  ['airtable',   'Airtable',            'No-code databases.',                                   'unicorn', 1440],
  ['plaid',      'Plaid',               'Bank account API layer.',                              'unicorn', 1500],
  ['canva',      'Canva',               'Design for non-designers.',                            'unicorn', 1500],
  ['discord',    'Discord',             'Voice/chat for communities.',                          'unicorn', 1520],
  ['databricks', 'Databricks',          'Lakehouse + Spark.',                                   'unicorn', 1620],
  ['gitlab',     'GitLab',              'DevOps platform; fully remote.',                       'unicorn', 1380],
  ['hashicorp',  'HashiCorp',           'Terraform, Vault, Nomad.',                             'unicorn', 1440],
  ['neon',       'Neon',                'Serverless Postgres.',                                 'unicorn', 1480],
  ['planetscale','PlanetScale',         'Serverless MySQL, Vitess.',                            'unicorn', 1500],
  ['warp',       'Warp',                'The terminal, reimagined.',                            'unicorn', 1540],
  ['raycast',    'Raycast',             'Launcher + extensions.',                               'unicorn', 1620],
  ['arc',        'The Browser Co.',     'Arc, then Dia.',                                       'unicorn', 1520],
  ['replit',     'Replit',              'Browser IDE, AI agents.',                              'unicorn', 1480],
  ['hex',        'Hex',                 'Notebooks for data teams.',                            'unicorn', 1500],
  ['posthog',    'PostHog',             'Open-source product analytics.',                       'unicorn', 1500],
  ['cursor',     'Cursor',              'AI-first code editor; the new hotness.',               'unicorn', 1780],
  ['loveable',   'Lovable',             'Prompt-to-app builder.',                               'unicorn', 1500],
  ['v0',         'v0 (Vercel)',         'Generative UI.',                                       'unicorn', 1560],
  // Public
  ['airbnb',     'Airbnb',              'Stays, design-led culture.',                           'public', 1560],
  ['uber',       'Uber',                'Rides, eats, freight.',                                'public', 1440],
  ['lyft',       'Lyft',                'Rides #2.',                                            'public', 1320],
  ['doordash',   'DoorDash',            'Local commerce delivery.',                             'public', 1400],
  ['instacart',  'Instacart',           'Grocery delivery, ads business.',                      'public', 1340],
  ['snap',       'Snap',                'Snapchat, Spectacles.',                                'public', 1380],
  ['pinterest',  'Pinterest',           'Visual discovery.',                                    'public', 1380],
  ['reddit',     'Reddit',              'Front page of the internet.',                          'public', 1460],
  ['spotify',    'Spotify',             'Audio, podcasts, ads.',                                'public', 1520],
  ['shopify',    'Shopify',             'Commerce platform.',                                   'public', 1580],
  ['block',      'Block',               'Square + Cash App.',                                   'public', 1380],
  ['coinbase',   'Coinbase',            'US crypto exchange.',                                  'public', 1440],
  ['roblox',     'Roblox',              'UGC gaming platform.',                                 'public', 1340],
  ['palantir',   'Palantir',            'Gotham, Foundry, AIP.',                                'public', 1500],
  ['snowflake',  'Snowflake',           'Data cloud.',                                          'public', 1560],
  ['mongodb',    'MongoDB',             'Document DB.',                                         'public', 1400],
  ['cloudflare', 'Cloudflare',          'Edge network, Workers.',                               'public', 1620],
  ['datadog',    'Datadog',             'Observability.',                                       'public', 1540],
  ['confluent',  'Confluent',           'Kafka, commercially.',                                 'public', 1380],
  ['twilio',     'Twilio',              'Comms APIs.',                                          'public', 1340],
  ['dropbox',    'Dropbox',             'Cloud storage. Quiet years.',                          'public', 1280],
  ['zoom',       'Zoom',                'Post-pandemic plateau.',                               'public', 1260],
  ['atlassian',  'Atlassian',           'Jira, Confluence, Trello.',                            'public', 1360],
  ['paypal',     'PayPal',              'Payments incumbent.',                                  'public', 1300],
  ['ebay',       'eBay',                'Marketplaces; long tail.',                             'public', 1240],
  ['yelp',       'Yelp',                'Local reviews.',                                       'public', 1180],
  ['etsy',       'Etsy',                'Handmade marketplace.',                                'public', 1240],
  ['robinhood',  'Robinhood',           'Retail brokerage.',                                    'public', 1340],
  ['sofi',       'SoFi',                'Consumer finance, public.',                            'public', 1280],
  ['affirm',     'Affirm',              'BNPL pioneer.',                                        'public', 1300],
  ['twitch',     'Twitch',              'Live streaming, Amazon-owned.',                        'public', 1340],
  // Hardware
  ['spacex',     'SpaceX',              'Rockets + Starlink. The dream job.',                   'hardware', 1780],
  ['anduril',    'Anduril',             'Defense tech, autonomous systems.',                    'hardware', 1620],
  ['rivian',     'Rivian',              'EV trucks.',                                           'hardware', 1320],
  ['lucid',      'Lucid',               'Luxury EVs.',                                          'hardware', 1240],
  ['boom',       'Boom Supersonic',     'Supersonic airliner.',                                 'hardware', 1440],
  ['joby',       'Joby Aviation',       'eVTOL air taxis.',                                     'hardware', 1380],
  ['relativity', 'Relativity Space',    '3D-printed rockets.',                                  'hardware', 1380],
  ['firefly',    'Firefly Aerospace',   'Smaller-payload launch.',                              'hardware', 1320],
  ['shield',     'Shield AI',           'Autonomy for defense.',                                'hardware', 1480],
  ['skydio',     'Skydio',              'Autonomous drones.',                                   'hardware', 1400],
  ['psg',        'Physical Intelligence','Robotics foundation models.',                         'hardware', 1620],
  ['onex',       '1X',                  'Humanoid robotics.',                                   'hardware', 1500],
  ['figureai',   'Figure',              'Humanoid robotics; OpenAI-adjacent.',                  'hardware', 1560],
  ['waymo',      'Waymo',               'Self-driving, finally shipping.',                      'hardware', 1640],
  ['cruise',     'Cruise',              'GM’s AV bet, in retreat.',                        'hardware', 1180],
  ['zoox',       'Zoox',                'Amazon’s purpose-built AV.',                      'hardware', 1300],
  ['neuralink',  'Neuralink',           'BCI implants.',                                        'hardware', 1500],
  ['psiquantum', 'Psi Quantum',         'Photonic quantum computing.',                          'hardware', 1380],
  ['ionq',       'IonQ',                'Trapped-ion quantum.',                                 'hardware', 1300],
  ['cerebras',   'Cerebras',            'Wafer-scale AI chips.',                                'hardware', 1480],
  ['groq',       'Groq',                'LPU inference chips.',                                 'hardware', 1500],
  ['sambanova',  'SambaNova',           'AI infrastructure.',                                   'hardware', 1280],
  // Startups
  ['supermaven', 'Supermaven',          'Code completion; acquired by Anthropic.',              'startup', 1500],
  ['stackblitz', 'StackBlitz',          'Bolt; in-browser dev.',                                'startup', 1480],
  ['codeium',    'Codeium / Windsurf',  'AI IDE.',                                              'startup', 1540],
  ['exa',        'Exa',                 'Search for AI agents.',                                'startup', 1460],
  ['cartesia',   'Cartesia',            'Real-time voice models.',                              'startup', 1500],
  ['suno',       'Suno',                'AI music generation.',                                 'startup', 1520],
  ['elevenlabs', 'ElevenLabs',          'AI voice cloning.',                                    'startup', 1580],
  ['pika',       'Pika',                'Generative video.',                                    'startup', 1380],
  ['decagon',    'Decagon',             'AI customer support agents.',                          'startup', 1440],
  ['sierra',     'Sierra',              'Bret Taylor’s agents company.',                   'startup', 1520],
  ['harvey',     'Harvey',              'AI for law.',                                          'startup', 1480],
  ['glean',      'Glean',               'Enterprise AI search.',                                'startup', 1500],
  ['writer',     'Writer',              'Enterprise gen AI.',                                   'startup', 1400],
  ['rox',        'Rox',                 'AI for sellers.',                                      'startup', 1380],
  ['clay',       'Clay',                'GTM data tooling.',                                    'startup', 1500],
  ['attio',      'Attio',               'Modern CRM.',                                          'startup', 1460],
  ['vanta',      'Vanta',               'Compliance automation.',                               'startup', 1520],
  ['drata',      'Drata',               'Also compliance.',                                     'startup', 1380],
  ['turso',      'Turso',               'Edge SQLite.',                                         'startup', 1400],
  ['railway',    'Railway',             'Heroku, but good.',                                    'startup', 1500],
  ['flyio',      'Fly.io',              'Edge VM platform.',                                    'startup', 1480],
  ['render',     'Render',              'Cloud app hosting.',                                   'startup', 1380],
  ['modal',      'Modal',               'Serverless GPUs.',                                     'startup', 1520],
  ['baseten',    'Baseten',             'Model deployment.',                                    'startup', 1420],
  ['pinecone',   'Pinecone',            'Vector DB.',                                           'startup', 1380],
  ['weaviate',   'Weaviate',            'Vector DB, OSS.',                                      'startup', 1340],
  ['neo4j',      'Neo4j',               'Graph database.',                                      'startup', 1300],
  // Crypto
  ['anchorage',  'Anchorage',           'Crypto custody.',                                      'crypto', 1300],
  ['polygon',    'Polygon Labs',        'Ethereum L2.',                                         'crypto', 1340],
  ['solanafnd',  'Solana Labs',         'High-throughput L1.',                                  'crypto', 1380],
  ['paradigm',   'Paradigm',            'Crypto VC.',                                           'crypto', 1500],
  ['uniswap',    'Uniswap Labs',        'DEX standard.',                                        'crypto', 1380],
  ['chainalysis','Chainalysis',         'On-chain analytics.',                                  'crypto', 1280],
  ['flashbots',  'Flashbots',           'MEV research.',                                        'crypto', 1440],
];

export const COMPANIES: CompanyBase[] = RAW.map(([id, name, tagline, sector, elo]) => ({
  id,
  name,
  tagline,
  sector,
  elo,
  startingElo: elo,
  votes: 0,
  wins: 0,
  losses: 0,
  cohortBias: defaultBias(sector),
}));
